### ISSUE TITLE
Unable to access modules for the upcoming semester

### ISSUE THREAD

**Issue by tysg** [fluminurs/fluminurs#617]
We are not officially in the new semester at the moment; so although I can access the new modules on LumiNUS, I cannot download the files via Fluminurs.

One way to solve this is to add a `term` CLI flag, that forces the program to fetch files for the specified term. For example:

```
fluminurs --term 2020 [...]
```

will force download files for AY20/21 Semester 2, despite we are officially still in Semester 1 as indicated by LumiNUS.

**Comment by btzy** [comment]
Can we fetch all terms >= current_term instead?  It's just a one character change, and it will probably do the "expected" thing for most use cases.
