### ISSUE TITLE
Separate out into library and CLI tool frontend like fluminus

### ISSUE THREAD

**Issue by indocomsoft** [fluminurs/fluminurs#62]
So people can write their own front-end

**Comment by juxd** [comment]
Hello, I'm trying to work on this issue. Not sure what's the best way to organise things, but this is what I have in mind:

```
fluminurs/
  src/
    lib.rs (previously api/mod.rs)
    module.rs (previously api/module.rs)
    bin/
      cli.rs (previously src/main.rs)
```

This means that it'll still be a single package (alternatively, we can consider [workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html), but I think this is not necessary). Also, the fluminurs cli bin would be renamed `fluminurs-cli`.

Let me know what you think about this organisation.
