### ISSUE TITLE
Not working on Linux by default as LumiNUS is sending an incomplete TLS certificate chain

### ISSUE THREAD

**Issue by angelsl** [fluminurs/fluminurs#621]
LumiNUS's TLS certificates got renewed in early December, and they seem to have configured their server with a certificate file containing only LumiNUS's certificate, without the intermediate DigiCert CA.

[![image](https://user-images.githubusercontent.com/235432/104121745-9cb32100-537b-11eb-843e-6748354646e5.png)](https://archive.is/xlHYi)

So any tool that relies on the system certificate store and is unable to download its own intermediate CAs will fail, including `curl`&mdash;try `curl https://luminus.nus.edu.sg`.

This is a misconfiguration on their end, but I'm not sure if they will ever fix it (I don't really have faith in NUS CIT, oops).

We have two options&mdash;bundle the intermediate CA in fluminurs or just ask Linux users to add the intermediate CA to their system trust store.

Any comments? Does anyone want to let CIT know?

**Comment by indocomsoft** [comment]
For reference, also happened to the Elixir fluminus https://github.com/indocomsoft/fluminus/pull/103 and Python pyfluminus https://github.com/raynoldng/pyfluminus/issues/5
