### ISSUE TITLE
Trailing spaces in folder name causes issues with file renaming

### ISSUE THREAD

**Issue by tysg** [fluminurs/fluminurs#633]
I'm using MacOS, here are some screenshots.
<img width="1108" alt="Screenshot 2021-01-22 at 11 33 38 AM" src="https://user-images.githubusercontent.com/42670338/105443171-07325e00-5ca6-11eb-819e-115036bcccde.png">
<img width="381" alt="Screenshot 2021-01-22 at 11 34 01 AM" src="https://user-images.githubusercontent.com/42670338/105443186-0f8a9900-5ca6-11eb-835b-f7a97317b2fa.png">

**Comment by btzy** [comment]
The Windows version trims spaces from both ends, maybe it should be standardized for other OSes too.

**Comment by tysg** [comment]
Turns out MacOS supports trailing spaces. The `(Unicode Encoding Conflict 1)` was added by Dropbox because Dropbox doesn't support it, thereby causing some conflict in the files. Nonetheless, trimming the names solves the problem.
