### ISSUE TITLE
Corruption when multiple files with the same filename and path are downloaded

### ISSUE THREAD

**Issue by thomastanck** [fluminurs/fluminurs#639]
I got a corrupt PDF when I tried to download this midterm-logistics.pdf file. There are two of them uploaded by the lecturer:

![image](https://user-images.githubusercontent.com/829070/109693266-6e580200-7bc4-11eb-8caa-0cdd439a366d.png)

When I downloaded it, I got this weird corrupted PDF:

![image](https://user-images.githubusercontent.com/829070/109693331-7dd74b00-7bc4-11eb-8aca-6ae3741f0caa.png)

I lacked the foresight to save a copy of the actual corrupt PDF, but I'm thinking this is simply what happens when two parallel downloads go to the same location.

**Comment by btzy** [comment]
Indeed, both the `name` and `fileName` fields are the same for these two files, so two threads are probably trying to write to the files simultaneously using different handles.  It is not clear what the "proper" fix for this should be... maybe we should ignore the older file and just download the newer one?
