### ISSUE TITLE
Unable to list/download multimedia files hosted on LumiNUS for some modules

### ISSUE THREAD

**Issue by ktaekwon000** [fluminurs/fluminurs#655]
Hi, I'm currently having problems listing/downloading multimedia for the module CS3203, where it outputs the error `Failed loading module multimedia: Invalid API response from server: type mismatch`. The videos are hosted on LumiNUS. This issue seems to be specific to CS3203, as fluminurs is able to download RC1010A and CS4226 videos fine (hosted on LumiNUS and Panopto multimedia respectively).

If the maintainers are not able to reproduce this with their mods, I might try to diagnose the problem but no guarantees as I am new to Rust/don't have a lot of time this sem 😅

**Comment by bnjmnt4n** [comment]
I think it would be helpful if you could just look at the network traffic in DevTools for LumiNUS API call matching `multimedia/?ParentID={}` and `multimedia/{}/medias`, and see if there are any differences with the API response types we expect here:
https://github.com/fluminurs/fluminurs/blob/68d0606089e0cdb62e6f4a2b4cce5a0cf200a0e8/src/multimedia/mod.rs#L18-L34

**Comment by ktaekwon000** [comment]
Thanks a lot for the guidance. There were no differences in the structure between the json and the structs, but the api call that fluminurs makes (https://github.com/fluminurs/fluminurs/blob/master/src/multimedia/mod.rs#L62) is different from the call that the luminus frontend makes, where the luminus frontend adds an extra URL parameter of `populate=contentSummary`. Attaching this URL parameter returns fewer channels, and modifying fluminurs to attach that parameter seems to fix my problem. I'll fork and make a PR soon.
