### ISSUE TITLE
External multimedia (and possibly weblecture) downloads seem to now be broken

### ISSUE THREAD

**Issue by btzy** [fluminurs/fluminurs#657]
I'm getting `Failed to download file: Unable to find video URL` printed to stdout, and on inspection it is because the Panopto page fetched by the external multimedia downloader does not contain a `<meta property="og:video" />` tag.

Perhaps Panopto changed its player to no longer include a direct link.  There is an .m3u8 stream though, so we might need to download using the stream instead.

I only have a single module (MA3238) using external multimedia - not sure if anyone else with external multimedia or weblectures have this issue too?

**Comment by bnjmnt4n** [comment]
Yeah, I've seen this issue also, but didn't have time to debug the response.

**Comment by bnjmnt4n** [comment]
@btzy Where are you seeing the reference to the .m3u8 stream?

**Comment by btzy** [comment]
@bnjmnt4n I saw it in the network tab of Chrome devtools.   It seems to be requested by a script though, so it might be a bit tricky.  I do see three requests (in this order):
- WebResource.axd?...
- master.m3u8?...
- index.m3u8

**Comment by btzy** [comment]
I missed some things out - somehow Chrome devtools doesn't list all the request anymore, though Firefox does.  I'm preparing a PR that that makes a POST request to DeliveryInfo.aspx to get the stream from there.
