### ISSUE TITLE
Allow explicit inclusion and exclusion of files from download

### ISSUE THREAD

**Issue by bnjmnt4n** [fluminurs/fluminurs#664]
Currently, you can't specify which files to download. Adding `--include "glob"` and `--exclude "glob"` would be very helpful in filtering out unwanted files.

**Comment by angelsl** [comment]
I actually had plans to write a file filter option.

Basically something like --filter=path/to/executable, and for every file to be downloaded it would execute the file and send via stdin a JSON payload detailing some information e.g. module code, path, filename, etc.

If the executable exit with exit code 0, then the file is downloaded, else it is skipped.

These glob options would be a simpler alternative to that. I think we can have both.

**Comment by bnjmnt4n** [comment]
The file filter option sounds cool as well. I can work on an implementation for the glob options, using a crate like https://lib.rs/crates/globset maybe.

**Comment by angelsl** [comment]
Sounds good.
